# Student Loan Risk with Deep Learning

In [74]:
# Imports
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report
from pathlib import Path

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `student-loans.csv` file into a Pandas DataFrame. Review the DataFrame, looking for columns that could eventually define your features and target variables.   

In [75]:
# Read the csv into a Pandas DataFrame
file_path = "https://static.bc-edx.com/ai/ail-v-1-0/m18/lms/datasets/student-loans.csv"
loans_df = pd.read_csv(file_path)

# Review the DataFrame
loans_df.head()

payment_history  location_parameter  stem_degree_score  gpa_ranking  \
0              7.4                0.70               0.00          1.9   
1              7.8                0.88               0.00          2.6   
2              7.8                0.76               0.04          2.3   
3             11.2                0.28               0.56          1.9   
4              7.4                0.70               0.00          1.9   

   alumni_success  study_major_code  time_to_completion  \
0           0.076              11.0                34.0   
1           0.098              25.0                67.0   
2           0.092              15.0                54.0   
3           0.075              17.0                60.0   
4           0.076              11.0                34.0   

   finance_workshop_score  cohort_ranking  total_loan_score  \
0                  0.9978            3.51              0.56   
1                  0.9968            3.20              0.68   
2                  0.9970            3.26              0.65   
3                  0.9980            3.16              0.58   
4                  0.9978            3.51              0.56   

   financial_aid_score  credit_ranking  
0                  9.4               0  
1                  9.8               0  
2                  9.8               0  
3                  9.8               1  
4                  9.4               0

In [76]:
# Review the data types associated with the columns
loans_df.dtypes

payment_history           float64
location_parameter        float64
stem_degree_score         float64
gpa_ranking               float64
alumni_success            float64
study_major_code          float64
time_to_completion        float64
finance_workshop_score    float64
cohort_ranking            float64
total_loan_score          float64
financial_aid_score       float64
credit_ranking              int64
dtype: object

In [77]:
# Check the credit_ranking value counts
loans_df["credit_ranking"].value_counts()

credit_ranking
1    855
0    744
Name: count, dtype: int64

### Step 2: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “credit_ranking”. The remaining columns should define the features dataset.

In [78]:
# Define the target set y using the credit_ranking column
y = loans_df['credit_ranking']

# Display a sample of y
y
# array([0, 0, 0, 1, 0])

0       0
1       0
2       0
3       1
4       0
       ..
1594    0
1595    1
1596    1
1597    0
1598    1
Name: credit_ranking, Length: 1599, dtype: int64

In [79]:
# Define features set X by selecting all columns but credit_ranking
X = loans_df.drop(columns='credit_ranking', axis=1)

# Review the features DataFrame
X.head()

payment_history  location_parameter  stem_degree_score  gpa_ranking  \
0              7.4                0.70               0.00          1.9   
1              7.8                0.88               0.00          2.6   
2              7.8                0.76               0.04          2.3   
3             11.2                0.28               0.56          1.9   
4              7.4                0.70               0.00          1.9   

   alumni_success  study_major_code  time_to_completion  \
0           0.076              11.0                34.0   
1           0.098              25.0                67.0   
2           0.092              15.0                54.0   
3           0.075              17.0                60.0   
4           0.076              11.0                34.0   

   finance_workshop_score  cohort_ranking  total_loan_score  \
0                  0.9978            3.51              0.56   
1                  0.9968            3.20              0.68   
2                  0.9970            3.26              0.65   
3                  0.9980            3.16              0.58   
4                  0.9978            3.51              0.56   

   financial_aid_score  
0                  9.4  
1                  9.8  
2                  9.8  
3                  9.8  
4                  9.4

### Step 3: Split the features and target sets into training and testing datasets.


In [80]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)


### Step 4: Use scikit-learn's `StandardScaler` to scale the features data.

In [81]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

---

## Compile and Evaluate a Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.


In [82]:
# Define the the number of inputs (features) to the model
input_nodes = X_train.columns

# Review the number of features
len(input_nodes)

11

In [83]:
# Define the number of hidden nodes for the first hidden layer
layer_one_nodes = 4

# Define the number of hidden nodes for the second hidden layer
layer_two_nodes = 8

# Define the number of neurons in the output layer
output_neurons = 1

In [84]:
# Create the Sequential model instance
nn_model = tf.keras.models.Sequential()

# Add the first hidden layer
nn_model.add(tf.keras.layers.Dense(units=layer_one_nodes, activation="relu", input_dim=len(input_nodes)))

# Add the second hidden layer
nn_model.add(tf.keras.layers.Dense(units=layer_two_nodes, activation="relu"))

# Add the output layer to the model specifying the number of output neurons and activation function
nn_model.add(tf.keras.layers.Dense(units=output_neurons, activation='sigmoid'))

c:\Users\mttca\nwuai\course_materials\class_work\challenges\neural-network-challenge-1\.venv\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [85]:
# Display the Sequential model summary
nn_model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_17 (Dense)                │ (None, 4)              │            48 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_18 (Dense)                │ (None, 8)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_19 (Dense)                │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 97 (388.00 B)

 Trainable params: 97 (388.00 B)

 Non-trainable params: 0 (0.00 B)

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.


In [86]:
# Compile the Sequential model
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [87]:
# Fit the model using 50 epochs and the training data
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.4058 - loss: 0.8605   
Epoch 2/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.4070 - loss: 0.7553 
Epoch 3/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.4831 - loss: 0.6998 
Epoch 4/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - accuracy: 0.5213 - loss: 0.6997
Epoch 5/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - accuracy: 0.6153 - loss: 0.6656
Epoch 6/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - accuracy: 0.6605 - loss: 0.6314
Epoch 7/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - accuracy: 0.6987 - loss: 0.6225
Epoch 8/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - accuracy: 0.6775 - loss: 0.6110
Epoch 9/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.6720 - loss: 0.6174
Epoch 10/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.6820 - loss: 0.6112
Epoch 11/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - accuracy: 0.7196 - loss: 0.5801
Epoch 12/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step 

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.


In [88]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
loss, accuracy = nn_model.evaluate(X_test_scaled, y_test, verbose=3)

# Display the model loss and accuracy results
print(f"loss: {loss}  |   accuracy: {accuracy}")

loss: 0.5328048467636108  |   accuracy: 0.7325000166893005


### Step 4: Save and export your model to a keras file, and name the file `student_loans.keras`.


In [89]:
# Set the model's file path
model_save_path = Path('student_loans.keras')

# Export your model to a keras file
nn_model.save(model_save_path)

---
## Predict Loan Repayment Success by Using your Neural Network Model

### Step 1: Reload your saved model.

In [90]:
# Set the model's file path
model_load_path = Path('student_loans.keras')

# Load the model to a new object
loaded_nn_model = tf.keras.models.load_model(model_load_path)


### Step 2: Make predictions on the testing data and save the predictions to a DataFrame.

In [91]:
# Make predictions with the test data
predictions = loaded_nn_model.predict(X_test_scaled)

# Display a sample of the predictions
predictions

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 


array([[0.49486256],
       [0.2651351 ],
       [0.90872145],
       [0.5484538 ],
       [0.9735825 ],
       [0.8664244 ],
       [0.9191931 ],
       [0.09807611],
       [0.8571451 ],
       [0.41703978],
       [0.89710987],
       [0.26988235],
       [0.34378308],
       [0.9747191 ],
       [0.38641027],
       [0.39990568],
       [0.8773418 ],
       [0.28967282],
       [0.5147556 ],
       [0.3086482 ],
       [0.5476252 ],
       [0.8957778 ],
       [0.28209564],
       [0.9215183 ],
       [0.3220119 ],
       [0.9257871 ],
       [0.83265996],
       [0.38624656],
       [0.41911346],
       [0.20258193],
       [0.2325729 ],
       [0.965814  ],
       [0.23927453],
       [0.95441073],
       [0.15536152],
       [0.5422399 ],
       [0.33623475],
       [0.3094249 ],
       [0.96924585],
       [0.26988235],
       [0.8930569 ],
       [0.21971692],
       [0.26847047],
       [0.8905703 ],
       [0.23937611],
       [0.55460894],
       [0.25785425],
       [0.381

In [92]:
tf.round(predictions)

<tf.Tensor: shape=(400, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
 

In [93]:
# Save the predictions to a DataFrame and round the predictions to binary results
predictions_df = pd.DataFrame(columns=["predictions"], data=tf.round(predictions))
predictions_df

predictions
0            0.0
1            0.0
2            1.0
3            1.0
4            1.0
..           ...
395          1.0
396          0.0
397          1.0
398          0.0
399          1.0

[400 rows x 1 columns]

### Step 4: Display a classification report with the y test data and predictions

In [97]:
# Print the classification report with the y test data and predictions
print(classification_report(y_test, tf.round(predictions)))

              precision    recall  f1-score   support

           0       0.68      0.81      0.74       188
           1       0.80      0.66      0.72       212

    accuracy                           0.73       400
   macro avg       0.74      0.74      0.73       400
weighted avg       0.74      0.73      0.73       400



---
## Discuss creating a recommendation system for student loans

Briefly answer the following questions in the space provided:

1. Describe the data that you would need to collect to build a recommendation system to recommend student loan options for students. Explain why this data would be relevant and appropriate.

2. Based on the data you chose to use in this recommendation system, would your model be using collaborative filtering, content-based filtering, or context-based filtering? Justify why the data you selected would be suitable for your choice of filtering method.

3. Describe two real-world challenges that you would take into consideration while building a recommendation system for student loans. Explain why these challenges would be of concern for a student loan recommendation system.

**1. Describe the data that you would need to collect to build a recommendation system to recommend student loan options for students. Explain why this data would be relevant and appropriate.**

#### **The data that I would collect to build a student loan recommendation system would be the person's: payment history - good to see where they are at in paying their current bills, previous GPA (high school) - might be good to see how they have previously done as a student, study major code - not all degrees are created equally, school ranking - does the school produce quality or are they there to just take the student's loan money. Median Salary for potential occupation/degree accross the nation you are predicting - some states have higher salaries, but higher costs of living.** 


**2. Based on the data you chose to use in this recommendation system, would your model be using collaborative filtering, content-based filtering, or context-based filtering? Justify why the data you selected would be suitable for your choice of filtering method.**

#### **Collaborative filtering: because you are looking at how others that share similar backgrounds in payment history, potential salary(median income)/degree are have performed in student loan repayments** 
#### **CContent-based filtering: I think this approach might work as well since it focuses on a single user and their previous interests/history** 


**3. Describe two real-world challenges that you would take into consideration while building a recommendation system for student loans. Explain why these challenges would be of concern for a student loan recommendation system.**

#### **1. The model isn't going to be able to predict human nature or unforseeable events - injuries, economic disasters, etc.** 
#### **2. The model is going strictly off data. If the model gives a higher weight to highschool GPA, but highschool GPA may not translate into post college success.** 